name: test

on:
  repository_dispatch:
    types: [ test ]
  workflow_dispatch:
    inputs:
      name:
        description: 'Description'
        required: false

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [ 3.10.8 ]
    steps:
      - uses: actions/checkout@v3

      - name: Get steamcmd
        run: |
          curl https://steamcdn-a.akamaihd.net/client/installer/steamcmd.zip --output steamcmd.zip
          Expand-Archive -Path steamcmd.zip

      - name: run
        run: |
          cd steamcmd
          steamcmd.exe +quit
        shell: cmd
        continue-on-error: true

      - name: run
        run: |
          cd steamcmd
          ls
          cd logs
          ls -l
          cat console_log.txt
          cat connection_log.txt
          cat configstore_log.txt
          cat bootstrap_log.txt
        shell: cmd
        continue-on-error: true